server.port: 8443

spring.application.name: api-gateway

api:
  auth-server:
    base-url: http://localhost:9999
  user-service:
    base-url: http://localhost:8081
  analytics-service:
    base-url: http://localhost:8082
  workout-service:
    base-url: http://localhost:8083
  exercise-service:
    base-url: http://localhost:8084

spring:
  cloud:
    gateway:
      routes:
        - id: oauth2-server
          uri: ${api.auth-server.base-url}
          predicates:
            - Path=/oauth2/**

        - id: user-service
          uri: ${api.user-service.base-url}
          predicates:
            - Path=/api/users/**,/api/auth/**

        - id: analytics-service
          uri: ${api.analytics-service.base-url}
          predicates:
            - Path=/api/analytics/**

        - id: workout-service
          uri: ${api.workout-service.base-url}
          predicates:
            - Path=/api/workouts/**

        - id: exercise-service
          uri: ${api.exercise-service.base-url}
          predicates:
            - Path=/api/exercises/**

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${api.auth-server.base-url}

  threads:
    virtual:
      enabled: true

management:
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: always
  endpoints:
    jmx:
      exposure:
        include: "*"

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.web.server.adapter.HttpWebHandlerAdapter: TRACE

---
spring.config.activate.on-profile: docker

api:
  auth-server:
    base-url: http://auth-server:9999
  user-service:
    base-url: http://user-service:8080
  analytics-service:
    base-url: http://analytics-service:8080
  workout-service:
    base-url: http://workout-service:8080
  exercise-service:
    base-url: http://exercise-service:8080